### PR TITLE
2kplus2.cpp compilation 

### PR DESCRIPTION
**Pull request by ayangromano**
Hello, 

When compiling 2kplus2, I received this error: 

2kplus2.cpp: In function ‘int main()’:
2kplus2.cpp:1657: error: ‘memset’ was not declared in this scope

What I did was add in "#include <cstring>" in the #include section [lines 28-42] and compilation ran smoothly. However, I also noticed that there is an #include <string> [line 30] in that section. When I changed <string> to <cstring>, compilation ran smoothly again. 

Depending on a computer's configuration, maybe <string> works for some and not others. In my case it did not work for me. I would suggest adding in "#include <cstring>" to that section as well.

Ashley

### CODE REVIEW

**Comment by wikilover** [comment]
hello！what platform and software should i run the program? VS2010?

**Comment by wikilover** [comment]
hello! when i execute './cortex_con_31 -k 31 -n 24 -b 85 -t fastq -c 100 -s 1 -i can0reads.txt -o can0_31_1_100_check.ctx -l can0_31_1_100_check.log', there is Error: file ./ERR031532_2.fastq is included more than once. how to solve it?

**Comment by redayounsi** [comment]
Hi,  It could be that you've added the link twice to the same fastq file.  Cortex has several error flags.  Try with only one file first in your path file can0reads.txt.  Otherwise try to compile cortex_con from the source and retry with the same command.  Thanks.

**Comment by redayounsi** [comment]
Compiled successfuly in Microsoft visual studio express 2013 on windows 8.1

**Pull request closed without merging**
